
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://icchfsixwdnylrnabznq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljY2hmc2l4d2RueWxybmFiem5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MTMxMDIsImV4cCI6MjA2MjM4OTEwMn0.Z9P3GO4rd5Fc0frdrZtS4X1Y4OWM2HuW7E_Vh336r5c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
