// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://klbctjhzazbcxwlbwmqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtsYmN0amh6YXpiY3h3bGJ3bXF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAzMTc3NDIsImV4cCI6MjA3NTg5Mzc0Mn0.x3HxjCmWKovCL36ZDEAtvW98TeCoqJSic8-pZ16CuIw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client"

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
